#!/usr/bin/env bash

conf=$2

mac() {
    echo "4E:53:50:4F:4F:$(printf '%02X\n' $(expr $(date -u +%s) / 180 % 160))"
}

update() {
    echo 'Updating MAC address'
    sed -i "s/bssid=.*/bssid=$(mac)/" $conf
}

run() {
    while true; do
        update
        /usr/bin/hostapd $conf &
        PID=$!
        sleep 180
        kill -KILL $PID
    done
}

status() {
    echo "Wanted MAC: $(mac)"
    echo "Actual MAC: $(grep 'bssid' "${conf}" 2>&1 | sed 's/bssid=//')"
}


case "$1" in
    update)
        update
        ;;
    run)
        run
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 update|run|status CONF"
        ;;
esac
